### ISSUE TITLE
결제 기한 확인 

### ISSUE THREAD

**Issue by hyeoktae** [final-project-fastflix/FDS#41]
**제안배경**
넷플릭스 맴버십 기한 다가오면 보임

**기능설명**
결제기한 확인용

**기대효과**
자신의 결제기한이 얼마나 남은 지 알수 있다.

**논의사항**
만들건가요???

<img width="1440" alt="스크린샷 2019-07-25 오후 6 52 43" src="https://user-images.githubusercontent.com/48010847/61865438-2ebc3500-af0e-11e9-96db-7d8dc1f9b0b7.png">

**Comment by Sub2n** [comment]
저희 멤버십이랑 결제기능 안 넣기로 해서 만들지 않습니다
